<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ModelicaStudio.Application/ModelicaStudio.Application.csproj" />
    <ProjectReference Include="../ModelicaStudio.Domain/ModelicaStudio.Domain.csproj" />
  </ItemGroup>
</Project>
